### ISSUE TITLE
Does not work for imported anonymous stateless functional components

### ISSUE THREAD

**Issue by bhargav175** [algolia/react-element-to-jsx-string#11]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

For components created using pure functions, the response is 'function(props) ....'.

**Comment by vvo** [comment]
Hi @bhargav175 do you think you can add a failing test case and submit a PR? Would be AWE-SOME

**Comment by bhargav175** [comment]
Sure, will give it a shot.

**Comment by bhargav175** [comment]
Doesn't work

     export default function(props){...}
Works

     export default function Flexbox(props){ ... }

**Comment by vvo** [comment]
I think there's no way to do what you want: the anonymous function has no function.name so we cannot render it to a string since we do not know the function name.

if you `console.log(<AnonymousStatelessComponent/>)` you will see that JSX did not find any name for the component so we cannot stringify it.

Is that clear? Do you have another idea?

**Comment by vvo** [comment]
I have reworked the PR, see the master

**Comment by vvo** [comment]
What we could do here is turn any anonymous component to render into a string like <No Display Name> and then  compare them. The comparison will work if you compare anonymous component.

What do you think?

**Comment by bhargav175** [comment]
Will it work? Like you said, I dont see any property of <AnonymousStatelessComponent> that we could use to figure out the name.

**Comment by vvo** [comment]
Also @bhargav175 I would advise you to always use named components because when you use react-dev-tool you will have the same issue as this module.

I will update it to make it work because it's an easy fix but please use named components

**Comment by vvo** [comment]
> Will it work?

Yes

**Comment by bhargav175** [comment]
Sure. Thanks @vvo .
