### ISSUE TITLE
Escape strings of HTML within <code> blocks

### ISSUE THREAD

**Issue by davidtheclark** [algolia/react-element-to-jsx-string#126]
I have an element that looks like this:

```js
{ 
  '$$typeof': Symbol(react.element),
  type: 'code',
  key: 'h-4',
  ref: null,
  props:
   { className: 'language-javascript',
     children: [ '<div style={{ color: pink }}>123459254321</div>\n' ] },
  _owner: null,
  _store: {} 
}
```

It's a `<code>` element with JSX inside of it. 

The output from this module gives no special treatment to the JSX within the `<code>` element, so it ends up coming out as regular JSX: `<code><div style=...></div></code>`. Re-render that JSX and you have something different than what you started with.

I think this situation could be represented in JSX like `<code>{'<div style=...'}</div>`. You could also escape the `<` `>` signs, maybe.

I also think the same problem would apply to HTML within `<code>` blocks.

Do you think I'm misunderstanding something, or is this a bug?

**Comment by Spy-Seth** [comment]
Could you provide of the JSX that will led to this  example of react element?

**Comment by davidtheclark** [comment]
@Spy-Seth: Here's some JSX that will produce the problem:

```js
<code>
  {'<div style={{ color: pink }}>123459254321</div>\n'}
</code>
```

That renders to the element object I pasted above. When you feed that element through this module, though, you come out with the following *very different* JSX:

```js
<code>
  <div style={{ color: pink }}>123459254321</div>

</code>
```

**Comment by davidtheclark** [comment]
@Spy-Seth that sounds like an excellent plan 👍
