### ISSUE TITLE
Don't fetch value from constant

### ISSUE THREAD

**Issue by schoenwaldnils** [algolia/react-element-to-jsx-string#131]
Example:
```js
// Button.js
export const PRIMARY = Symbol();

export default const Button = (props, children) => {
  switch (props.type) {
    case PRIMARY:
      theme = 'Button--primary';
      break;
  }
  return (<button className={ theme } { ...props }>{ children }</button>)
}
export default Button;
```

```js
// view code-block
import jsxToString from 'react-element-to-jsx-string';
import Button, {  PRIMARY } from 'Button.js';

console.log(jsxToString(<Button type={PRIMARY}>Primary</Button>))
```

My Problem is that the constant is not `PRIMARY` but `Symbol()`:
```js
<Button type={Symbol()}>
  Primary
</Button>
```

Is there a way to workaround that?

**Comment by Spy-Seth** [comment]
`react-element-to-jsx-string` already format Symbols ([see the test](https://github.com/algolia/react-element-to-jsx-string/blob/master/src/index.spec.js#L133)).

In your code you are generating anonymous symbol: `const foo = Symbol()`. To have a named symbol you need give it a descriptor: `const foo = Symbol('FOO')`.  

See the [Symbol docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol)

**Comment by schoenwaldnils** [comment]
ok, I got that. 
But still, now I see this:
```
<Button type={Symbol(PRIMARY)}>
  Primary
</Button>
```
but I expect this:
```
<Button type={PRIMARY}>
  Primary
</Button>
```

**Comment by Spy-Seth** [comment]
I'm not sure of what is the `PRIMARY` string in the output you propose.


If we have this: 
```jsx
const FOO = Symbol('BAR');

console.log(reactElementToJsxString(<Button type={FOO} />));
```

What did you expect as output?

```jsx
<Button type={FOO} />
```
 or 
```jsx
<Button type={BAR} />
```



One issue with your proposal is that this is not a valid JSX output: `<Button type={PRIMARY} />`. `PRIMARY` refers into a variable that will not be defined. 

The actual output is not JSX compliant neither 😅 We will need to fix it!

**Comment by schoenwaldnils** [comment]
I would expect this
```
<Button type={FOO} />
```
which is the constant-name from this:
```
import {  FOO } from 'FooBar.js';
```

**Comment by Spy-Seth** [comment]
I don't think it's possible. In JavaScript, we cannot retrieve the variable name from it's reference. And I not sure this is what we want. The aim of this library is to print a react element tree in a readable way.

**Comment by Spy-Seth** [comment]
I close this issue for now. If you have any comments on this do not hesitate I will reopen it 😃
