### ISSUE TITLE
Webpack / UglifyJS bundling process issue

### ISSUE THREAD

**Issue by dptoot** [algolia/react-element-to-jsx-string#140]
Thanks for the utility, it is/was working great!  

I am utilizing it in a custom addon for react-storybook.  Until I upgraded react-storybook to their webpack 2 update it seemed to be working fine.  But I am having an issue now with webpack/babel/uglify build of react-storybook processing this package.  Digging into it this may not be an issue with react-element-to-jsx-string but really its stringify-object dependency.

[https://github.com/yeoman/stringify-object/issues/35](https://github.com/yeoman/stringify-object/issues/35)

It seems that the compiled version was not intended for browser usages and it's compiled file is shipped containing arrow functions that will break within uglify since it won't process ES2015.

Is anyone else experiencing browser usage issues?  I tried processing stringify-object with babel as part of the build but to no avail.  Being that it is a dependency of a dependency I am not sure that the end user would be responsible or aware of how to use this properly...

Any ideas, suggestions, or solutions would be appreciated.

Thanks again!

**Comment by dptoot** [comment]
Apparently this package's usage has already been called out within stringify-object's issues as well

https://github.com/yeoman/stringify-object/issues/36

**Comment by bguggie** [comment]
have you tried uglify-es:
https://github.com/mishoo/UglifyJS2/tree/harmony
... supposed to handle uglifying es6+

**Comment by dptoot** [comment]
I could perhaps use another minifier if I use the full control mode of storybook but at this time the minifier is baked in to their build target.

**Comment by Spy-Seth** [comment]
Hi @dptoot,

For now we do not target browser usage for this project. As you're not the first to open an issue on this subject (https://github.com/algolia/react-element-to-jsx-string/issues/90) maybe we should consider it? 

@vvo What did you think about this?

**Comment by vvo** [comment]
> have you tried uglify-es:
> mishoo/UglifyJS2@harmony
> ... supposed to handle uglifying es6+

This is the right answer to this current issue, you could maybe contribute to storybook default minifier and use uglify-es as stated here: https://github.com/mishoo/UglifyJS2#note

Other relevant links:
https://github.com/yeoman/stringify-object/issues/35
https://github.com/storybooks/storybook/issues/1570
https://github.com/storybooks/storybook/pull/1668

I am sorry this happens but stringify-object may have take this decision (of not building anymore for ES5) a bit too early. OR uglifyjs may have waited too long to implement changes to support ES6.

Either way, you have solution to fix this I believe in the post you saw.

Thanks a lot for contributing here!
