### ISSUE TITLE
Array.includes is not supported in Internet Explorer

### ISSUE THREAD

**Issue by sawyerh** [algolia/react-element-to-jsx-string#147]
The library [includes several calls](https://github.com/algolia/react-element-to-jsx-string/search?q=.includes&type=Code&utf8=%E2%9C%93) to the [Array.prototype.includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) method, which breaks compatibility with Internet Explorer (including IE11)

**Comment by sawyerh** [comment]
Ah, sorry. I see the [note about requiring ES2015 environments](https://github.com/algolia/react-element-to-jsx-string#environment-requirements) so I'm guessing this is a known, wontfix, issue. I got around this by installing [core-js](https://github.com/zloirock/core-js) and requiring the following in my file:

```js
require('core-js/fn/array/includes');
require('core-js/fn/array/fill');
require('core-js/fn/function/name');
require('core-js/fn/object/get-own-property-symbols');
require('core-js/fn/string/includes');
```

**Comment by Spy-Seth** [comment]
You're right, this project does not target an ES5 environment so you have to polyfill what's needed!
