### ISSUE TITLE
Ability to configure how to show the component's display name

### ISSUE THREAD

**Issue by leoasis** [algolia/react-element-to-jsx-string#15]
Some times you want to have control on how to display components' names. When you have components wrapped in a higher order component, sometimes it makes sense to just hide that when rendering the JSX and just show the original component's name (i.e. when rendering to a string that will be used as the markup example in a styleguide). This should not only be configurable for top level components, but also for all the components appearing as props in any level. I think probably providing a function that receives an element and returns the display name as part of some options to provide to the `reactElementToJSXString` function, would be the right API.

What do you think?

**Comment by vvo** [comment]
Hi @leoasis, indeed that could be a good addition.

I would be happy to review a PR with tests for something like this:

```js
reactElementToJSXString(el, {displayName: fn});
```

When fn would receive the current element that we want to choose a name for.

**Comment by vvo** [comment]
What are you using react-element-to-jsx-string for? Thanks

**Comment by leoasis** [comment]
Cool, I'll look into doing something today or maybe tomorrow!

I'm currently using it for showing the JSX of examples in a live styleguide, aka component catalog. Since I have _themeable_ components, and the theming logic is being abstracted in a higher order component (with the theme styles being passed down as props), what I actually have are `Themed(Component)` kind of display names that I'd want to change when rendering the example JSX string
