### ISSUE TITLE
On windows machines, get an error: Array.prototype.sort callback must be a function

### ISSUE THREAD

**Issue by oveddan** [algolia/react-element-to-jsx-string#17]
On my mac, and on our linux CI server, using karma and phantom js 2.0 and this library, we do not get an error.

We have the requirement to deploy the code onto a windows pc.  When running tests on that pc, using phantom 2.0 and windows 8.1, we get an error:

> TypeError: Array.prototype.sort callback must be a function
>     at Array.sort (base/node_modules/es5-shim/es5-shim.min.js:6:10070)
>     at sortObject (base/src/test_helpers/requires/test_index.js:28145:36)
>     at stringifyObject (base/src/test_helpers/requires/test_index.js:7968:42)
>     at formatValue (base/src/test_helpers/requires/test_index.js:7945:58)
>     at formatJSXAttribute (base/src/test_helpers/requires/test_index.js:7929:19)
>     at getJSXAttribute (base/src/test_helpers/requires/test_index.js:7920:15)
>     at base/src/test_helpers/requires/test_index.js:7913:15
>     at Array.map (native)
>     at formatProps (base/src/test_helpers/requires/test_index.js:7912:58)
>     at toJSXString (base/src/test_helpers/requires/test_index.js:7852:18)
>     at base/src/test_helpers/requires/test_index.js:7956:15
>     at Array.map (native)
>     at toJSXString (base/src/test_helpers/requires/test_index.js:7893:63)
>     at reactElementToJSXString (base/src/test_helpers/requires/test_index.js:7833:11)
>     at Assertion.includeJSX (base/src/test_helpers/requires/test_index.js:7769:45)
>     at Assertion.assert (base/src/test_helpers/requires/test_index.js:3979:50)

**Comment by vvo** [comment]
What is the version of react-element-to-jsx-string you are using?

**Comment by oveddan** [comment]
2.2.0

**Comment by vvo** [comment]
Can you try 2.4.0 (latest) thx
