### ISSUE TITLE
newlines on windows

### ISSUE THREAD

**Issue by tugend** [algolia/react-element-to-jsx-string#18]
Hi. 

I suggest replacing the "\n" chars with a platform-dependent newline,
i.e. if on node ``var endOfLine = require('os').EOL;`` 

As evident in the screenshot here from [expect-jsx](https://github.com/algolia/expect-jsx), the current way of formatting the output will be a problem to read for larger components. I guess the explicit '\n' chars are meant to be printed as newlines instead and this is a general bug occurring on windows machines?

Right now I just use ``.replace(/\\n/g, "\r\n")``.

If it's not a quick fix, let me know and I'll make a pull-request. ^_^

Cheers

**Comment by vvo** [comment]
> I guess the explicit '\n' chars are meant to be printed as newlines instead and this is a general bug occurring on windows machines?

No that's just a side effect of expect library I believe. Ultimately I would want not to have the duplicated inline expectation/formatted one just below but dunno how to do it (help appreciated in expect-jsx project).

> var endOfLine = require('os').EOL;

Yes this is a great idea! Send a PR :)

**Comment by tugend** [comment]
You're absolutely right, I'll try to make a pull request to 'chai-jsx' instead (which depend on expect-jsx).
My apologies, ^_^

Cheers.

**Comment by vvo** [comment]
Not sure we are on the same line here, I do think a PR that would move from '\n' to the system newline would be cool. send it here :)

**Comment by tugend** [comment]
Sure thing, I had a look at it, and it's pretty easy to add,
but I sincerely think it might be against best-practice for node module.

1)
It turns out that my problem was because the chai assertion library prints symbols in the comparison text, which is actually a prefered feature in cases where the test fails because of meta symbols i.e. 

```js
expected '<div>\n</div>'  to equal '<div>\r\n</div>'
```

vs 

```js 
expected 

'<div>
<\div>'  

to equal 

'<div>
<\div>'
```

2)
When printing ``\n`` in node, the linebreaks are rendered regardless of platform, and when you parse a string with linebreaks it's read as ``\n`` even on Windows machines, i.e. it seems to be the default and expected behavior in node to use ``\n`` regardless of platform.

The following test would fail on windows if we implemented platform dependent linebreaks

```js
 expect(`<div>\r\n  String with 1 js number \r\n</div>`).toEqual(`<div>
  String with 1 js number
</div>`) // fails because second expression parses with '\n' 
```

```js
 expect(`<div>\n  String with 1 js number \n</div>`).toEqual(`<div>
  String with 1 js number
</div>`) // pass
```

**Comment by vvo** [comment]
Ok so it seems we do not need to do anything but maybe expect-jsx and $lib-jsx should provide:
1. Error message like "JSX output is different"
2. Full JSX comparison as details
