### ISSUE TITLE
Flow issues

### ISSUE THREAD

**Issue by pascalduez** [algolia/react-element-to-jsx-string#214]
Hi,

`react-element-to-jsx-string@13.0.0`
`flow-bin@0.52.0`

Seeing a bunch of errors from test files:
https://gist.github.com/pascalduez/d65bb067d7dca36e336a6572c7b55af7

So I went with:
```
[ignore]
<PROJECT_ROOT>/node_modules/react-element-to-jsx-string/.*\.spec
```

But still getting some:
https://gist.github.com/pascalduez/098b2dabf914b8b3e9ccbee03613fcfa

I guess the optional options should be set as .. optional?

**Comment by Spy-Seth** [comment]
Hi @pascalduez,

We have recently upgrade to the latest version of flow. I suppose this could be a source of the issue. Lot's of important change in flow v0.53 and more. Could you give a try in a recent version of flow?
