### ISSUE TITLE
Avoid to have to require the `default` module when requiing

### ISSUE THREAD

**Issue by armandabric** [algolia/react-element-to-jsx-string#271]
Following the comment: https://github.com/algolia/react-element-to-jsx-string/pull/269#discussion_r157343884

Avoid to have to require the `default` module when requiring the library:

```jsx
const foo = require('react-element-to-jsx-string').default; // not pretty

const foo = require('react-element-to-jsx-string'); // pretty
```

**Comment by danoc** [comment]
I think this one can be closed.
