### ISSUE TITLE
Props that differ from their defaults not rendered when showDefaultProps option is false

### ISSUE THREAD

**Issue by beauroberts** [algolia/react-element-to-jsx-string#28]
First, thanks for creating such a great utility! Now, onto the issue I've run into:

Taking a component used in the tests:

```jsx
class DefaultPropsComponent extends React.Component {}

DefaultPropsComponent.defaultProps = {test: 'test'};
```

The following case correctly omits the prop from the JSX string:

```jsx
reactElementToJSXString(<DefaultPropsComponent />, {showDefaultProps: false})
// <DefaultPropsComponent />
```

But if you change the prop's value from the default, it doesn't get rendered:

```jsx
reactElementToJSXString(<DefaultPropsComponent test="foo" />, {showDefaultProps: false})
// <DefaultPropsComponent />
```

I would expect the result to be

```jsx
// <DefaultPropsComponent test="foo" />
```

I'm just about to submit a pull request with a test and a fix.

**Comment by vvo** [comment]
LGTM

cc @slightlytyler You might be interested by this fix, can you have a quick look (you implemented that option)

**Comment by vvo** [comment]
> First, thanks for creating such a great utility!

:pray: THX. I :heart: contributions

**Comment by vvo** [comment]
Well this seems good and fits the documentation. Thanks a lot.

**Comment by slightlytyler** [comment]
@vvo huh, I thought I handles this case 😓 LGTM now though

**Comment by vvo** [comment]
No big deal, all fixed now!
