### ISSUE TITLE
Can not minify due to stringify-object dependency not targeting browsers

### ISSUE THREAD

**Issue by jonthomp** [algolia/react-element-to-jsx-string#285]
I'm trying to use this within a [create-react-app](https://github.com/facebook/create-react-app/) project but am hitting build issues due to the dependency on [stringify-object](https://github.com/yeoman/stringify-object/).

The [issue is that they don't provide an ES5 compiled version](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) and are [apparently not willing to do so](https://github.com/yeoman/stringify-object/issues/35#issuecomment-272376517).

Any chance of changing to an alternative dependency or just building in a compiled version of stringify-object rather than relying on the dependency?

**Comment by jonthomp** [comment]
After trying out https://github.com/algolia/react-element-to-jsx-string/pull/242 it resolves the issue so I'll just be using that for now

**Comment by danoc** [comment]
@jonthomp — Any luck? The latest version (14.0.0) doesn't seem to work with the older version of Uglify I'm using through Gatsby.

**Comment by danoc** [comment]
I believe this is also related to: https://github.com/algolia/react-element-to-jsx-string/issues/211

**Comment by vvo** [comment]
@DanielHoffmann Can you use a more recent version of Uglify with Gatsby?

**Comment by pascalduez** [comment]
Fixed in #288 and #292

**Comment by danoc** [comment]
Can confirm that this now works with older versions of Uglify.
