### ISSUE TITLE
API request: filterFunction

### ISSUE THREAD

**Issue by adamduncan** [algolia/react-element-to-jsx-string#286]
The `filterProps` option is helpful, but lacks the ability to dynamically filter props based on anything other than their name.

What if the API included a `filterFunction` option, that would take propNames and allow us to pass our own filter function body? That way we could also filter out props based on more dynamic criteria. E.g. the prop's value, or the props type.

For example:

```
reactElementToJSXString(element, {
  filterProps: ['onClick'], // useful in scenarios when you know the specific prop names
  filterFunction: propName => typeof element.props[propName] !== 'function' // don't render props which are functions
  // or
  filterFunction: propName => !element.props[propName] // don't render props that have falsy values (e.g. empty strings)
})
```

Thanks for your work on this library!

**Comment by vvo** [comment]
Good idea. I would go for `filter`, as a function yes, deprecate filterProps with a warning and in docs.

Accepting PRs to solve that @adamduncan gogogo!
