### ISSUE TITLE
don't publish .babelrc

### ISSUE THREAD

**Issue by blaenk** [algolia/react-element-to-jsx-string#33]
I get an error when I build my project with webpack because it says it can't find the babel plugin `stage-2` which is specified in react-element-to-jsx-string's `.babelrc`. It is my understanding that this file shouldn't be published to npm at all since it's only used to build the ES6 code which is then published. I depend on chai-enzyme which depends on this, and this ends up breaking my webpack build.

Searching around I found [this](https://github.com/callemall/material-ui/issues/3200) which seems to resolve it by being specific about which files are published to the npm registry, by specifying something like `"files": "./index-dist.js"`.

This way the `.babelrc` won't end up on the user's system, so babel won't attempt to obey it. I had to remove the `.babelrc` file myself from `node_modules/react-element-to-jsx-string/.babelrc` to resolve this.

**Comment by blaenk** [comment]
It was a mistake on my end actually.

**Comment by vvo** [comment]
You need to exclude node_modules from browserify/webpack
