### ISSUE TITLE
Displaying template literals for code component

### ISSUE THREAD

**Issue by danoc** [algolia/react-element-to-jsx-string#34]
Hello!

I have this React component:

```js
      <Code type="block">
{`var foo = 'bar';
var bat = 'baz';`}
      </Code>
```

The template literal is transpiled to ES5 and the `props.children` becomes a string like this:

```js
var foo = 'bar';
var bat = 'baz';
```

When displaying this string in our documentation, it ends up looking like this:

![screenshot 2016-07-18 17 49 57](https://cloud.githubusercontent.com/assets/916038/16934955/189505ee-4d10-11e6-9857-20d672974581.png)

This is a problem because copying and pasting the source code would not produce the desired multiline output.

It doesn't seem like there is any functionality that allows us to re-add the template literals. Is this something that this project would like to support or has any known workarounds?

If not, I suppose I could check to see if it is the code component and modify the children string to include the template literals.

Thanks for all the hard work! This is a great project and we're happily using for [our documentation site](http://design.optimizely.com/docs/oui/13.0.1/react/).

**Comment by vvo** [comment]
> This is a problem because copying and pasting the source code would not produce the desired multiline output.
> 
> It doesn't seem like there is any functionality that allows us to re-add the template literals. Is this something that this project would like to support or has any known workarounds?

Thanks for using react-element-to-jsx-string. I am down for adding more feature but I do not see an easy way to do what you want. If you have any API idea to do so, propose it then implement it, add tests and :boom:!

We already had many contributors so no problem at all if you want to add a new feature.

**Comment by danoc** [comment]
Thanks @vvo! I'm not sure if I have a good fix for this, so feel free to close it.

I'll post here once I have a somewhat hacky workaround in place.

**Comment by spence-novata** [comment]
Could you not provide a Component that can provide a string value to inject in to the code string?

```
import reactElementToJSXString, { EscapedString } from 'react-element-to-jsx-string'

<Code type="block">
  <EscapedString value={`var foo = 'bar';
var bat = 'baz';`} />
</Code>
