### ISSUE TITLE
Option to do not escape JSON string

### ISSUE THREAD

**Issue by lufego** [algolia/react-element-to-jsx-string#409]
Hi, I use this library together with Storybook to display what's the original source code of my components so other people can copy and past and use it somewhere else. 

As I said I need to display the source code for the component. The thing is that one of the props is a JSON string, and it has double quotes inside. But when the source code gets rendered, they are replace by `&quot;`.

Is there any way to avoid it?

![image](https://user-images.githubusercontent.com/14938754/64172324-fe44b080-ce54-11e9-801b-4f606e830fd4.png)

**Comment by Spy-Seth** [comment]
Hi @lufego ,

I have use `react-element-to-jsx-string` the same way than you in the past, and it should work fine. We even have tests for this specific feature: https://github.com/algolia/react-element-to-jsx-string/blob/a291b8856718400298b2467060939a8f47a18dee/src/index.spec.js#L231-L249

In you exemple, are you sure you are passing the `srcset` attribute as an array/object and not as a string to your component?

**Comment by armandabric** [comment]
No answer so let's close this.
