### ISSUE TITLE
Problems with displayName

### ISSUE THREAD

**Issue by rtfpessoa** [algolia/react-element-to-jsx-string#445]
Following code fails when it tries to create display name `Uncontrolled(Dropdown)` instead of just `Dropdown`
```tsx
// react-bootstrap version 0.32.4
import { Dropdown, MenuItem } from 'react-bootstrap';
// react-element-to-jsx-string latest version
import reactElementToJSXString from 'react-element-to-jsx-string';

reactElementToJSXString(
    <Dropdown id="dropdown-custom-1">
        <Dropdown.Toggle bsStyle="primary">
            <i className="fa fa-filter"></i>
        </Dropdown.Toggle>
        <Dropdown.Menu>
            <MenuItem eventKey="1" active>Action</MenuItem>
            <MenuItem eventKey="2">Another action</MenuItem>
            <MenuItem eventKey="3">Something else here</MenuItem>
        </Dropdown.Menu>
    </Dropdown>
);
```

Any ideas why, or how this can be fixed?

**Comment by Spy-Seth** [comment]
After having a look in our code and the `uncontrolled` library, it seems they create a proxy element that have the new name you want `Uncontrolled(...)` but this proxyfied element does not proxy the element type that why we guess the original component name `Dropdown`


For memories:
- https://github.com/jquense/uncontrollable/blob/6b33be778da043718089f059186e8fbb843f6be9/src/uncontrollable.js#L7
- https://github.com/jquense/uncontrollable/blob/6b33be778da043718089f059186e8fbb843f6be9/src/uncontrollable.js#L110-112

In the next days I have no time to have a look into it. A PR is welcome, or if you want you could use the `displayName` option of `reactElementToJsxString(<Foo />, {displayName: () => 'Bar'})` and manually guess the component name 
You could reuse the our own detection has a base:

https://github.com/algolia/react-element-to-jsx-string/blob/071e2e5e573d44a8ff42520be1270f312d5ac430/src/parser/parseReactElement.js#L15-L20

**Comment by rtfpessoa** [comment]
@Spy-Seth thanks for the quick answer.
You suggestions are exactly what I did to quickly fix it on my side, but I had to hack it since I could not find a good way to find the real. In sum I removed the `Uncontrolled()` from the name and got only what is inside parenthesis.

Do you have any suggestion on how we could do a proper fix?

**Comment by Spy-Seth** [comment]
I miss understand you. I was thinking that you wanted `Uncontroled(Dropdow)` in the output, but in fact that what you have. 

In that case, I think the only solution is that you hack on your side with the `displayName` option. 

This is a special HOC behavior of the react-bootstrap library, I'm not sure it's a good think for us to do a dedicated development for this as we already have the `displayName` for theses kinds of use cases.
