### ISSUE TITLE
Linting errors when globally installed eslint is out of date

### ISSUE THREAD

**Issue by beauroberts** [algolia/react-element-to-jsx-string#47]
Hi! Thanks for an awesome tool!

I noticed a bunch of linting errors were popping up in my IDE, and it turns out that it's because I had a super old version of eslint globally installed. I was able to sort these out by installing the `eslint` and `eslint-plugin-react` packages as devDependencies.

I'll submit a tiny pull request in case it's useful.

**Comment by vvo** [comment]
Thanks, relevant information: https://github.com/algolia/eslint-config-algolia/commit/b18724e67b6254c55053e59cbd904b3ad1b05d00
