### ISSUE TITLE
Add a TypeScript declaration file

### ISSUE THREAD

**Issue by goloroden** [algolia/react-element-to-jsx-string#474]
Hey there 👋 

This module is really helpful, so first thanks for creating and maintaining it!

Unfortunately, there is no TypeScript declaration file included, and AFAICS there is also no typings package on `@types`. Could you imagine adding such a file to this module?

This would help a lot when this module is used from TypeScript.

PS: I could also imagine to come up with a PR, but I have seen that you are using flow, and I was not sure if you would like to have a TypeScript declaration file at all, so I just wanted to ask first.

**Comment by goloroden** [comment]
PPS: Okay, I thought that probably it's a good thing to have TypeScript types here, so I just created a PR: https://github.com/algolia/react-element-to-jsx-string/pull/475

**Comment by Spy-Seth** [comment]
The PR have been merge (thanks again for having taking care of it). I'm releasing it 🚀

**Comment by Spy-Seth** [comment]
🚀 https://github.com/algolia/react-element-to-jsx-string/releases/tag/v14.2.0
