### ISSUE TITLE
Error TS2305: Module '"react-element-to-jsx-string"' has no exported member 'Options'

### ISSUE THREAD

**Issue by leonelgalan** [algolia/react-element-to-jsx-string#514]
_**storybookjs/addon-jsx**_ fails when updating from `14.1.0` to `14.3.0` with the error above, because the following line:

```tsx
import reactElementToJSXString, { Options } from 'react-element-to-jsx-string';
```

I'm not familiar with publishing types, but I believe the error is because related to [index.d.ts](https://github.com/algolia/react-element-to-jsx-string/blob/master/index.d.ts) not exporting `ReactElementToJSXStringOptions`, perhaps as `Options`?

**Comment by Spy-Seth** [comment]
Hi @leonelgalan,

When you said that `storybookjs/addon-jsx` fails, what is failing? The build? or the type checking?

In v14.2, we recently added the `index.d.ts` files to help TS users: https://github.com/algolia/react-element-to-jsx-string/pull/475. It's possible there is some issue with it. 


I think there was an issue with the line: 
```
import reactElementToJSXString, { Options } from 'react-element-to-jsx-string';
```

We never export the type `Options` in flow. So I'm sure what was the content of this variable was (and the import should have been `import { type Options }`). 

That said, we should probably export in flow and TS the options type.

**Comment by leonelgalan** [comment]
The build fails with  the error above: 

```
src/index.tsx:4:35 - error TS2305: Module '"react-element-to-jsx-string"' has no exported member 'Options'.

4 import reactElementToJSXString, { Options } from 'react-element-to-jsx-string';
```

My wild guess is that flow exported it implicitly, because it was part of the signature of the default function exported. 

For TS, this seems to work:

```diff
diff --git a/index.d.ts b/index.d.ts
index c2bc46a..83ff4c6 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -13,7 +13,8 @@ declare module 'react-element-to-jsx-string' {
     sortProps?: boolean;
     useFragmentShortSyntax?: boolean;
   }
+  export { ReactElementToJSXStringOptions as Options };

   const reactElementToJSXString: (element: ReactNode, options?: ReactElementToJSXStringOptions) => string;
-  export = reactElementToJSXString;
+  export default reactElementToJSXString;
 }
```

I was able to use the new filterProps by linking (`yarn link`) this project and building _**storybook-addon-jsx**_.

**Comment by Spy-Seth** [comment]
The PR #516 should fix this

**Comment by Spy-Seth** [comment]
I just publish `react-element-to-jsx-string@14.3.1` with TS type fix. Keep me posted if there is any issue
