### ISSUE TITLE
Release new version compatible with React 17

### ISSUE THREAD

**Issue by alexandernst** [algolia/react-element-to-jsx-string#580]
React 17 was just released. There are no breaking changes, but if I try to use it with this package, I get warnings about missing peer-dependencies (this package depends on react@16.x).

Can you release a new version making this package compatible with React 17? @Spy-Seth

**Comment by alexandernst** [comment]
I'll gladly create a MR if you're willing to merge it and release a new version :)

**Comment by Spy-Seth** [comment]
A PR is welcome, I will release quickly after its merge

**Comment by alexandernst** [comment]
@Spy-Seth Done! https://github.com/algolia/react-element-to-jsx-string/pull/581

**Comment by Spy-Seth** [comment]
Thanks for your PR!

**Comment by Spy-Seth** [comment]
:rocket: react-element-to-jsx-string@14.3.2 just published

**Comment by alexandernst** [comment]
Great!!! \o/

Just one more thing @Spy-Seth . Is the yarnpkg updated automatically based on the npm registry? Or do you need to update it there too? (I'm asking as I still see the 14.3.1 being the latest version in yarnpkg)

**Comment by Spy-Seth** [comment]
There is nothing to do usually. Just wait a little for yarn to upgrade it's cache
