### ISSUE TITLE
Compound components lose parent reference

### ISSUE THREAD

**Issue by AndrewLeedham** [algolia/react-element-to-jsx-string#594]
It seems when using compound components the parent reference is lost. I created a repro here: https://repl.it/@AndrewLeedham56/react-element-to-jsx-compound-component-repro#index.jsx

```jsx
console.log(
  reactElementToJSXString(
    <Component>
      <Component.Compound text="Hello World!"/>
    </Component>
  )
);
// Outputs
/*
<Component>
  <Compound text="Hello World!" />
</Component>
*/
```

I was expecting it to output:
```jsx
<Component>
  <Component.Compound text="Hello World!" />
</Component>
```

**Comment by Spy-Seth** [comment]
Hi @AndrewLeedham, thanks to report this. 

When your create a component with the `<Component.Compound text="Hello World!" />` in fact you a using the `Component.Compound` expression as a reference to the function `Compound` attached to the Object `Component`.  When executed at run time, the referenced function get named by the attribute name `Compound`, the parent object `Component` is lost.

If you do:
```js
console.log(<Component.Compound text="Hello World!" />);
```

You will see something like this:
<img width="593" alt="Capture d’écran 2021-02-22 à 22 31 14" src="https://user-images.githubusercontent.com/95120/108772766-b7bda700-755d-11eb-9a82-8213bdb15394.png">

There is no way to determine the original JSX component name in that case.

**Comment by AndrewLeedham** [comment]
Thanks for the explainer @Spy-Seth makes sense. I had a poke around in the code for this and it seems it uses `displayName` so I managed to override the Babel auto-generated version with essentially `Component.Compound`, and it works. Fairly straightforward albeit somewhat hacky workaround for my use case :+1:
