### ISSUE TITLE
Option to not render values

### ISSUE THREAD

**Issue by areknow** [algolia/react-element-to-jsx-string#604]
Not sure how to word it exactly, sorry about that..

I would like to show the code:
```
<Button
  onChange={() => {
    setCount(count + 1);
  }}
>
  clicked: {count}
</Button>
```
But instead I am getting the rendered value of `{count}`:
<img width="718" alt="Screen Shot 2021-03-15 at 5 11 41 PM" src="https://user-images.githubusercontent.com/6361609/111221923-8448c800-85b1-11eb-94cd-3e688f76831a.png">

Is this possible?
Thanks!

**Comment by armandabric** [comment]
Hi @areknow,

Your exemple will transpiled to something like this:

```js
React.createElement(Button, { onChange: () => setCount(count + 1) }, `clicked: ${count}`);
```

The third argument will be resolved a runtime to became the string `clicked: 2`. So it's not possible for the library to retrieve it.
