### ISSUE TITLE
[object Object] displayName for React.forwardRef components

### ISSUE THREAD

**Issue by g12i** [algolia/react-element-to-jsx-string#615]
`React.forwardRef` creates an object with a rendering function moved to a .render property ([see here](
https://github.com/facebook/react/blob/main/packages/react/src/ReactForwardRef.js)).

```js
function forwardRef(render) {
  return {
     $$typeof: REACT_FORWARD_REF_TYPE,
    render,
  };
}

```

I'd suggest to use [react-is](https://www.npmjs.com/package/react-is) package and copy logic from React's [shared/getComponentNameFromType.js](https://github.com/facebook/react/blob/main/packages/shared/getComponentNameFromType.js)

```js
import { isForwardRef } from "react-is";

function getWrappedName(
  outerType: mixed,
  innerType: any,
): string {
  const displayName = (outerType: any).displayName;
  if (displayName) {
    return displayName;
  }
  return innerType.displayName || innerType.name || 'No Display Name';
}


const getReactElementDisplayName = (element: mixed): string => {
  if (isForwardRef(element)) {
    return getWrappedName(element, (element as any).type);
  }
  // .. .etc
};

```

**Comment by armandabric** [comment]
This should be fixed by #617. Let me know if this is not the case. Meanwhile I'm closing this issue.
