### ISSUE TITLE
Boolean props with a default value of `true` are not rendered when the value is `false`

### ISSUE THREAD

**Issue by beauroberts** [algolia/react-element-to-jsx-string#67]
If you create a component with a default boolean prop set to `true`, like this:

```jsx
class DefaultPropsComponent extends React.Component {}

DefaultPropsComponent.defaultProps = {test: 'test', something: true};
```

and then render an instance of that component where the prop is `false`:

```jsx
reactElementToJSXString(<DefaultPropsComponent something={false} />, {showDefaultProps: false})
// Result: <DefaultPropsComponent />
```

the resulting string does not include `something={false}` as expected.

I'll submit a PR momentarily!

**Comment by pascalduez** [comment]
I just updated to `5.0.4` but still can't get a `foobar={false}` to render.

I will try to narrow down to a bare repo example.

**Comment by vvo** [comment]
Ok that would be great, maybe it did not build properly? Check what's inside node_modules and let us know, feedback counts!
