### ISSUE TITLE
production jsx string not correct 

### ISSUE THREAD

**Issue by rimsila** [algolia/react-element-to-jsx-string#671]
```tsx 
in dev mode  <Pricing2 />
prod mode:  <i />
```

after build it remain only i

**Comment by IagoAugusto** [comment]
Did you find a solution for that? This is happening to me in production but I don't what it may be.

**Comment by rimsila** [comment]
> Did you find a solution for that? This is happening to me in production but I don't what it may be.

I want to use it in react library for demo by showing jsx usage and copy to clipboard but it working only in development. I hope I can use it in production build also it save my time on re-write jsx code again that you

**Comment by tu4mo** [comment]
Try using displayName for components or disable function name mangling in your minifier.

**Comment by rimsila** [comment]
> Try using displayName for components or disable function name mangling in your minifier.

Thanks you It working now after displayName to component

**Comment by bacali95** [comment]
@rimsila if you are using `react-scripts` for building, adding `--profile` to `react-scripts build` will keep the class names and also functions names for production profiling. I tried it and it works for me :grin:
