### ISSUE TITLE
Error isPlainObject is not a function

### ISSUE THREAD

**Issue by IvanovRoman** [algolia/react-element-to-jsx-string#687]
If using compile file index.js version `cjs`. An error `isPlainObject.isPlainObject is not a function`.

Part code in index.js (cjs)
```
if (isPlainObject.isPlainObject(propValue) || Array.isArray(propValue)) {
    return "{".concat(formatComplexDataStructure(propValue, inline, lvl, options), "}");
  }
```

**Comment by anguspiv** [comment]
I am seeing this same issue in my code:

version: `"react-element-to-jsx-string": "^14.3.4",`
browser error stack:

```
index.js:375 Uncaught TypeError: isPlainObject.isPlainObject is not a function
    at formatPropValue (index.js:375)
    at formatProp (index.js:390)
    at index.js:547
    at Array.forEach (<anonymous>)
    at formatReactElementNode (index.js:546)
    at formatTreeNode (index.js:691)
    at formatTree (index.js:702)
    at reactElementToJsxString (index.js:741)
    at Example (Example.js:79)
    at renderWithHooks (react-dom.development.js:12740)
```

looking at the [source code (formatPropValue.js L63)](https://github.com/algolia/react-element-to-jsx-string/blob/d37c7e9883414d6c55235593e5e5c3152699d398/src/formatter/formatPropValue.js#L63) the original code reads:
```js
  if (isPlainObject(propValue) || Array.isArray(propValue)) {
```

but the built and distributed code (index.js L375) reads: 
```js
  if (isPlainObject(propValue) || Array.isArray(propValue)) {
    return "{".concat(formatComplexDataStructure(propValue, inline, lvl, options), "}");
  }
```

I checked the tag code here on github, and the src looks correct as well, so not sure why the compiled code is converting to `isPlainObject.isPlainObject`

**Comment by anguspiv** [comment]
Looking into this more, I was able to downgrade to 14.3.2 to temporarily fix the issue for myself. I think this has to do with the upgrade of `is-plain-object` to 5.0.0

**Comment by IvanovRoman** [comment]
> Looking into this more, I was able to downgrade to 14.3.2 to temporarily fix the issue for myself. I think this has to do with the upgrade of `is-plain-object` to 5.0.0

Thanks. The problem was misuse `node_modules`. I redid `resolve.modules` in `main.js` for storybook.
```
config.resolve.modules = [
      ...config.resolve.modules,
      path.resolve(__dirname, '..', 'src'),
    ];
```
