### ISSUE TITLE
Add .babelrc to .npmignore file

### ISSUE THREAD

**Issue by DanielHoffmann** [algolia/react-element-to-jsx-string#69]
Hi I am using your library and for some reason my webpack build process is picking up your .babelrc file making my builds fail because I don't have all the plugins and presets you use in your library. This shouldn't be happening because my code is not building your library (and the plugins/presets from your library are under devDependencies), your library is compiled before publishing to `index-dist.js` so I shouldn't need any of your build-process stuff. If I remove `project_root/node_modules/react-element-to-jsx-string/.babelrc` file the build works as normal.

So all we need to do to fix these problems is adding a .npmignore file in the repository:
```
.babelrc
```

And republish the project to NPM.

Also thanks for the lib, pretty neat.

**Comment by vvo** [comment]
@DanielHoffmann Can you dig a bit more this issue? Normally if you do not try to transpile node_modules then there's little chance babel tries to read node_modules/**/.babelrc so there might be something else going wrong here?

**Comment by DanielHoffmann** [comment]
@vvo Yes you are correct, it is just that for some project-specific reasons my project webpack configuration doesn't exclude `node_modules` from `babel-loader`. But in any case adding an `.npmignore` file in the project is recommended (you probably should add all files except `index-dist.js` and `package.json to it) to reduce install sizes.

Sorry if I didn't make it clear before, this is not a bug in your library, but rather a problem with my code. But the fix for this problem is recommended practice.

**Comment by vvo** [comment]
@DanielHoffmann I am willing to accept a PR doing just that. Thanks!

**Comment by DanielHoffmann** [comment]
@vvo Done! The PR is published to NPM under `react-element-to-jsx-string-test` if you want to test it

**Comment by vvo** [comment]
was released

**Comment by DanielHoffmann** [comment]
@vvo Many thanks!
