### ISSUE TITLE
Support Symbol prop types

### ISSUE THREAD

**Issue by Xiphe** [algolia/react-element-to-jsx-string#72]
As a developer I want to use Symbols as prop types

Given I have a component `<Button />`
And I want to give that component a type "Primary"
And I use `const TYPE_PRIMARY = Symbol('TYPE_PRIMARY')` to specify a button type
And I have the following react element `{ ...otherAttributes, props: { type: TYPE_PRIMARY } }`
And I pass  through react-element-to-jsx-string

Then I expect the resulting jsx string to be `<Button type={TYPE_PRIMARY} />`

But I get an error "Uncaught TypeError: Cannot convert a Symbol value to a string"

---

I understand that we do not have the actual variable name that is used, and we can not be sure that the symbols name is mapping to that.

I'd propose to add a way to extend `formatValue` via options, so that I as user of this lib, can decide that on my own.

**Comment by vvo** [comment]
I have very little to no-knowledge of symbols so any PR supporting them is very welcomed, along with different strategies to handle them before maybe? Thanks!
