### ISSUE TITLE
Update react peerDependencies for React 18

### ISSUE THREAD

**Issue by markhughes** [algolia/react-element-to-jsx-string#728]
Could we update the peerDependencies to allow React 18?

```diff
  "peerDependencies": {
--    "react": "^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1",
++    "react": "^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1 || ^18.0.0",
--    "react-dom": "^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1"
++    "react-dom": "^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1  || ^18.0.0"
  },

**Comment by daelynj** [comment]
I am also hoping for this change.

**Comment by jttry** [comment]
> I am also hoping for this change.

+1

**Comment by markhughes** [comment]
Hey @armandabric I've put together the change and even added smoke tests (works fine): https://github.com/algolia/react-element-to-jsx-string/pull/729

**Comment by armandabric** [comment]
The support of React 18 is release in v15.0.0. Please give feedback if you have issue with it.
