### ISSUE TITLE
This package is no longer compatible with `react-dom@<15.5.0`

### ISSUE THREAD

**Issue by wesleytodd** [algolia/react-element-to-jsx-string#78]
We had to pin back to `6.3.0` to get this to work.  It is requiring `react-dom/test-utils`, which doesn't exist.  You should update your package json to remove the peer dep version range for these, and maybe add something to the readme.

**Comment by wesleytodd** [comment]
Also, this should be a major version bump.  If I were you I would deprecate `6.4.0`, publish a `6.4.1` which reverts the change, then publish `7.0.0` with the change from commit 1a99024b5dd52128e92301803f86752906718aa0.

**Comment by vvo** [comment]
Just released 7.0.0 and deprecated 6.4.0, thx
