### ISSUE TITLE
React elements nested in array/object props contain unnecessary string escaping

### ISSUE THREAD

**Issue by beauroberts** [algolia/react-element-to-jsx-string#80]
Hi - thanks for an awesome tool!

I think this might be a regression but I'm not sure when it would have been introduced. I'm having issues with unnecessary string escaping on props that contain React elements with single quotes (e.g. `<div object={{ nested: <div array={['hello', 'you']} /> }} />`

I'll submit a pull request with a failing test but unfortunately I'm not able to investigate a fix right now. If no one else can look into it, I might get around to it in a few days:

```diff
+ expected - actual

  <div
    obj={{
-     nested: <div arr={[\'hello\', \'you\']} />
+     nested: <div arr={['hello', 'you']} />
    }}
   />
```

**Comment by vvo** [comment]
cc @shouze maybe?

**Comment by vvo** [comment]
might be a regression yes
