### ISSUE TITLE
Array.prototype.fill

### ISSUE THREAD

**Issue by Sinewyk** [algolia/react-element-to-jsx-string#9]
Array.prototype.fill polyfill is not ~~standard~~ implemented everywhere yet.

```
'undefined' is not a function (evaluating 'new Array(times).fill('  ')')
```

Make a note about it in the README ?

**Comment by vvo** [comment]
Ah yes I think I made the assumption that everyone was using babel BUT that's not a good assumption. I will import fill from a polyfill. Do you mind trying to do a PR?

**Comment by vvo** [comment]
Something like

```js
import fill from 'lodash/array/fill';
```

**Comment by Sinewyk** [comment]
Oh yeah, nice, forgot lodash is always becoming more awesome.

**Comment by Sinewyk** [comment]
Had a bit of trouble to find it on npm, you have to go to https://www.npmjs.com/browse/keyword/lodash-modularized and search pages by hand it seems :o ...

Couldn't find it from search box :disappointed: 

But here you are.

**Comment by vvo** [comment]
thx! will publish
