### ISSUE TITLE
UglifyJS throw 'Invalid assignment' error

### ISSUE THREAD

**Issue by jmorrice** [algolia/react-element-to-jsx-string#90]
Hi,

Thanks for this awesome library!

I'm creating a component library using an nwb boilerplate (https://github.com/insin/nwb/blob/master/docs/guides/ReactComponents.md#developing-react-components-and-libraries-with-nwb).

Once I added react-element-to-jsx-string the build fails with the following error:
```
Failed to compile with 1 error.

 ERROR  in demo.1990f3e7.js from UglifyJs
Invalid assignment [./~/stringify-object/index.js:6,0][demo.1990f3e7.js:11007,34]
```

Is this an issue with stringify-object?

**Comment by vvo** [comment]
> Is this an issue with stringify-object?

Yes this is the case, search on their repo and let us know!

**Comment by jmorrice** [comment]
Already checked and was unable to find anything, that's why I submitted it here. Any ideas what could be causing this?

**Comment by vvo** [comment]
uglifyjs does not supports minifying ES2015 (this is sad) and stringify-object is not transpiled to ES5.

![image](https://user-images.githubusercontent.com/123822/27544984-f19d88f2-5a8e-11e7-9bfc-c46732849e5b.png)

I found this on uglifyjs website, maybe try https://github.com/mishoo/UglifyJS2/tree/harmony and let me know!

**Comment by vvo** [comment]
Or try this: https://github.com/babel/babili

**Comment by vvo** [comment]
Reopen another issue if you still have the issue, with a repro repository

**Comment by xuopled** [comment]
@jmorrice I have the same issue, what was your solution?

The only way I found was to disable `uglifyJS`

**Comment by xuopled** [comment]
the bug is not present with the original repo `https://github.com/alexlande/react-to-jsx`

**Comment by vvo** [comment]
> The only way I found was to disable uglifyJS from nwb config

This seems to be the way to go, you could also ask nwb to use the latest uglifyjs on their repo because more and more libraries will start shipping ES6

**Comment by xuopled** [comment]
Thank you, I asked for it

**Comment by jmorrice** [comment]
Thanks guys!
